package com.example.gymtracker.Model;

public class AlleUebungen {
    public static String[] alleErdenklichenUebungen = {
            "Bankdrücken",
            "Kniebeugen",
            "Kreuzheben",
            "Schulterdrücken",
            "Bizepscurls",
            "Trizepsdrücken",
            "Latziehen",
            "Rudern",
            "Beinpressen",
            "Wadenheben",
            "Crunches",
            "Russian Twist",
            "Plank",
            "Lunges",
            "Seitheben",
            "Arnold Press",
            "Ausfallschritte",
            "Frontheben",
            "Klimmzüge",
            "Dips",
            "Hammer Curls",
            "Bauchpresse",
            "Trizepsdips",
            "Side Plank",
            "Beinheben",
            "Beinpresse",
            "Beinbeuger",
            "Beinstrecker",
            "Hammer Strength Maschine",
            "Cable Crossover",
            "Seitheben am Kabelzug",
            "Rückenstrecker",
            "Bankdrücken mit Kurzhanteln",
            "Frontheben mit Kurzhanteln",
            "Schulterdrücken mit Kurzhanteln",
            "Kreuzheben mit Kurzhanteln",
            "Kniebeugen mit Kurzhanteln",
            "Seitheben mit Kurzhanteln",
            "Rudern mit Kurzhanteln",
            "Ausfallschritte mit Kurzhanteln",
            "Bizepscurls mit Kurzhanteln",
            "Trizepsdrücken mit Kurzhanteln",
            "Beinpressen",
            "Hackenschmidt-Kniebeugen",
            "Unterarmcurls",
            "Wadenheben am Seilzug",
            "Cable Crunches",
            "Face Pulls",
            "Reverse Flys",
            "Front Squats",
            "Sumo Deadlifts",
            "Skull Crushers",
            "Chest Flys",
            "Leg Extensions",
            "Hamstring Curls",
            "Pull-Ups",
            "Wide Grip Pull-Ups",
            "Close Grip Pull-Ups",
            "Box Jumps",
            "Bulgarian Split Squats",
            "Incline Bench Press",
            "Decline Bench Press",
            "Arnold Curls",
            "Preacher Curls",
            "Cable Rows",
            "Pulldowns",
            "Calf Raises",
            "Romanian Deadlifts",
            "Seated Shoulder Press",
            "Upright Rows",
            "Cable Crunches",
            "Plank Variations",
            "Russian Twists",
            "Oblique Crunches",
            "Leg Press",
            "Dumbbell Pullovers",
            "Incline Dumbbell Press",
            "Decline Dumbbell Press",
            "Dumbbell Lunges",
            "Dumbbell Step-Ups",
            "Dumbbell Front Raises",
            "Dumbbell Lateral Raises",
            "Dumbbell Bent Over Rows",
            "Dumbbell Hammer Curls",
            "Dumbbell Tricep Extensions",
            "Dumbbell Flys",
            "Dumbbell Leg Curls",
            "Dumbbell Goblet Squats",
            "Dumbbell Shoulder Press",
            "Dumbbell Upright Rows",
            "Dumbbell Farmers Walk",
            "Dumbbell Bulgarian Split Squats",
            "Dumbbell Incline Bench Press",
            "Dumbbell Decline Bench Press",
            "Dumbbell Shrugs",
            "Mountain Climbers",
            "Burpees",
            "Jumping Jacks",
            "Plank Jacks",
            "Bicycle Crunches",
            "Russian Twists",
            "High Knees",
            "Butt Kicks",
            "Wall Sits",
            "Side Lunges",
            "Side Planks",
            "Scissor Kicks",
            "Superman Holds",
            "Tricep Dips",
            "Pike Push-Ups",
            "Leg Raises",
            "Hollow Body Hold",
            "Flutter Kicks",
            "Crab Walk",
            "Bear Crawls",
            "Donkey Kicks",
            "Fire Hydrants",
            "Glute Bridges",
            "Bird Dogs",
            "Reverse Lunges",
            "Box Squats",
            "Bulgarian Split Squats",
            "Pistol Squats",
            "Lateral Lunges",
            "Single-Leg Deadlifts",
            "Plank Variations","Side Plank", "Forearm Plank", "Extended Plank",
            "Diamond Push-Up" ," Decline Push-Up",
            "Sumo Squat" , "Goblet Squat", "Jump Squat",
            "Chin-Up", "Wide Grip Pull-Up", "Commando Pull-Up",
            "Dips","Parallel Bar Dips", "Bench Dips",
            "Hanging Leg Raises",
            "Russian Twist with Medicine Ball",
            "Farmer's Walks",
            "Overhead Press",
            "Renegade Rows"
    };


}
